### ISSUE TITLE
OYT website enhancements 

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#109]
Change location of the Connect with Mee button:
1. Login screen -> It should go after Login or create an account -> then we put  ___or___ and locate there an email address field + Continue button 
Then we add another ___or___ and place there “Continue with Google/Facebook/Apple”. These buttons do nothing in terms of functionality. 
![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/6194cd27-bee3-49e7-ac46-c6b7eac867dc)

2. Checkout Screen -> Change location of the Connect with Mee button 
It should go after Login or create an account -> then we put  ___or___ and locate there an email address field + Continue button 

![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/2de43630-250e-47e0-b5b2-bf63c95b1da2)

Subscribe button has to have price on it
![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/6717a91c-d56d-4ef2-b057-e161efb6bccc)

**Comment by Silenthunt0** [comment]
Done
