### ISSUE TITLE
Privacy Badger Extension - Research

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#141]
Privacy Badger is a browser extension that stops advertisers and other third-party trackers from secretly tracking where you go and what pages you look at on the web. If an advertiser seems to be tracking you across multiple websites without your permission, Privacy Badger automatically blocks that advertiser from loading any more content in your browser. 

https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp

Basically, it is about having a black list of trackers and cutting the cookies (3d party cookies - discuss it with Paul if we need it). 

We need to put the research results into a table to be able to review what the extension functionality is about. 
After that, it is necessary to discuss the research results with Paul. 

Research points:

- Does the Privacy Badger extension have a black list?
- Does the Privacy Badger extension deal with fingerprinting? 
- Which browsers are supported?
- Etc 

Eventually, we would need to develop a similar extension to improve the level of privacy for the Mee users (we should find a way to stop the websites from stealing personal data). 

After the research part is done, provide the high-level implementation estimates and the scope of work.

**Comment by lemind** [comment]
Privacy Badger is a browser extension that automatically learns to block invisible trackers.

1. Browsers - chrome, ff, ff on android, opera, edge
2. How It works. It finds trackers and has [red/yellow/green lists](https://privacybadger.org/#What-do-the-red%2c-yellow-and-green-sliders-in-the-Privacy-Badger-menu-mean). But the key difference from similar that Privacy Badger is an algorithmic tracker blocker – we define what “tracking” looks like, and then Privacy Badger blocks or restricts domains that it observes tracking in the wild. It can use "remote learning" or "local learning". So it has big knowledge base and "learning"
3. Sending [Do Not Track](https://www.eff.org/issues/do-not-track) and [Global Privacy Control](https://globalprivacycontrol.org/) signals
4. [Prevent fingerpringint](https://privacybadger.org/#Does-Privacy-Badger-prevent-fingerprinting).
