### ISSUE TITLE
Google Topics API - Research

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#144]

**Comment by lemind** [comment]
Topics API
Third-party cookies are being phased out. Collects too much data.

With the Topics API, the browser observes and records topics that appear to be of interest to the user, based on their browsing activity. This information is recorded on the user's device.

The browser infers topics for a user based on their browsing activity during a period of time known as an epoch, currently one week. To further enhance privacy and ensure that all topics may be represented, there is a 5% chance the topic is randomly selected from all possible topics in a [taxonomy](https://github.com/jkarlin/topics/blob/main/taxonomy_v1.md) of interests.

Topics are selected from a [taxonomy](https://github.com/jkarlin/topics/blob/main/taxonomy_v1.md) consisting of hierarchical categories such as [/Arts & Entertainment/Music & Audio/Soul & R&B](https://github.com/patcg-individual-drafts/topics/blob/main/taxonomy_v1.md#:~:text=/Arts%20%26%20Entertainment/Music%20%26%20Audio/Soul%20%26%20R%26B)
For 10,000 top sites, the Topics API implementation in Chrome uses a manually curated, publicly available [override list](https://developer.chrome.com/docs/privacy-sandbox/topics/topic-classification/#classifier-model) to map hostnames to topics.
For other sites, the Topics API uses a [machine learning](https://royalsociety.org/topics-policy/projects/machine-learning/what-is-machine-learning-infographic/) model to infer topics from hostnames.[1]

A design goal of the Topics API is to enable interest-based advertising without sharing information with more entities than is currently possible with third-party cookies. The Topics API is designed so topics can only be returned for API callers that have already observed them, within a limited timeframe. 


















[1] https://developer.chrome.com/en/docs/privacy-sandbox/topics/overview/#manually-curated
