### ISSUE TITLE
How Mee Works link - arrange redirect back 

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#161]
Once a user clicks the How Mee Works link in the footer, they are redirected here - https://docs-dev.mee.foundation/
Please make it possible for users to come back to the Mee website home page once they click the Mee logo within the [Docs portal ](https://docs-dev.mee.foundation/)

**Comment by lemind** [comment]
https://github.com/MeeFoundation/docs/pull/5
