### ISSUE TITLE
Change progress bar location on page

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#36]
Consider options:

- The progress bar can be at the top, above the Header
- The progress bar can be located at the left side of the screen 

Discuss to come up with the final choice.

**Comment by lemind** [comment]
The header also solved the issue with disappearing text so it can get under the progress bar.
And if we decided move progress above the header it should be applied for all pages.
I am not sure we want it, let's discuss it 
@marimariavi

**Comment by marimariavi** [comment]
@lemind thank you for the comment!
The problem is that the progress bar somehow changes the color of the background, especially in the Mee restoring balance section. Please see the screenshots attached. 
If we can fix it without moving the progress bar above the header - would be great. If no - then consider an option of moving it up above the header. 


![Screenshot 2023-05-12 at 11 45 16 AM](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/ce39cf88-0644-484d-b21a-9605163e6157)
![Screenshot 2023-05-12 at 11 45 02 AM](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/daf2e180-0a43-4110-a699-831f5c34497a)

**Comment by lemind** [comment]
@marimariavi 
It was announced by Roman as far as I remember that he colored the header init gradient color. With that we solved issue about transparent header and distinctive blurred letters.

**Comment by marimariavi** [comment]
@lemind 
Got it. Let's discuss it with the team tomorrow. Thank you!

**Comment by marimariavi** [comment]
@lemind 
I have updated the description of this issue. Now it is only about the need to change the scroll bar element location.
