### ISSUE TITLE
Possible bug: scroll fails sometimes after reaching white section 

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#39]
Paul: "there seems to be a bug with the scrolling on the home page. Sometimes you can scroll from the top through each section (purple, explosion, light color), but at other times you can only scroll through the purple section and then it stops (no explosion). I’ll try to find a way to repeat this bug."

**Comment by lemind** [comment]
What browser is that? We should have a clear case to investigate.

**Comment by marimariavi** [comment]
Personally I had a similar issue in the Safari browser. 
I will double-check with Paul regrading his specific case.
