### ISSUE TITLE
Adjustment to consider: white section scroll 

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#41]
- The white stage of the landing page on is very unclear, there is no scroll indicator, no clue for what the user should do and it is also repeating the logo on the same screen.
- A user tried to tap the logo in the middle instead of keep scrolling; another user decided that the story is over and wanted to click the menu.
- Consider adding the mouse icon to the white section as well.

**Comment by lemind** [comment]
@marimariavi 
The BottomButton we can not get down without scrolling, also different screens and the animation make things with scrolling complex. Let's understand why we want to scroll all content on our main presentation page. 
If the reason to get the subscribe btn we can consider put it to header menu for example.

The mouse icon was added

**Comment by marimariavi** [comment]
@lemind 
there are a few reasons behind this scrollto - quickly reach the footer with Docs, download buttons, Connect with Mee button. Returning users most probably would want to skip the whole story about Mee. So we need to allow them skipping it.

**Comment by lemind** [comment]
@marimariavi Completely agree that user should have access to all that. If user does not want to get all the story we should give him/her links you mentioned without seeing the story. Some of the links we have already on the header. We can consider put Download and Connect with mee to header also.
And we have the explosion also.
Let's discuss on the meeting

**Comment by marimariavi** [comment]
@lemind yes, let's discuss it with the whole team and collect opinions on how to manage this. Thank you!
