### ISSUE TITLE
Mobile/Web version - bugs 

### ISSUE THREAD

**Issue by marimariavi** [MeeProject/mee-foundation-website#88]
1. About US page - Join us section. 
In the mobile version there is no padding and the text sticks to edges. 
![2023-06-06 20 32 04](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/68a63be5-17a2-48d6-bd8a-874cf5ab325b)
2. Underlined text should be consistent across the website. Example: 
![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/43b282b7-0cd3-4545-9998-f684f5d3b82d)
![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/686445c1-498d-4934-af99-5d9cc3751f99)
![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/7d1700cc-f980-425f-814e-fc5fd62d8ade)
How in looks in the mockups:
![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/490429e9-4d01-40ed-b755-ecdd9f6fd792)
![image](https://github.com/MeeFoundation/mee-foundation-website/assets/102594157/ce824ea9-02bc-49f0-b73a-0f58620c2c47)

It applies to both versions (mobile and web). 
In the mobile version some titles doesn't have an underline (for example, About us page). 

3. Make DIF logo (Partners section) be not colored, but in a black/white stile to keep it consistent with other logos

**Comment by lemind** [comment]
1,3 were fixed before

**Comment by marimariavi** [comment]
perfect! thanks a lot!
